const lang = {
    eng: {
        CurrencyConverter : "Currency Converter",
        Status: "Online Status",
        Home: "Home", 
        LogOut: "LogOut",
        About : "About",
        FromCurrency: "From Currency:",
        ToCurrency:"To Currency:",
        Amount: "Amount",
        Convert : "Convert",
        Profile: "Profile",
        Pay : "Pay",
        SignIn : "Sign In",
        EnterYourName: "Enter Your Name",
        EnterYourEmailAddress:"Enter your Email Address",
        EnterPassword: "Enter Password",
        SignUp: "Sign Up",
        EnterPin: "Enter Pin",
        MakeAtransaction: "Make a Transaction",
        Currency: "Currency",
        SixDigPin: "6- Digit Pin",
        Reason: "Reason",
        MakePayment:"Make Payment",
        ChangePassword: "Change Password",
        ChangePin: "Change Pin",
        Balance: "Balance",
        Email: "Email",
        Username: "Username",
        UserId: "User ID",
        Edit: "Edit",
        Security:"Security",
        PaidTo:"Paid To",
        AmountAndCurrencyDuringPayment: "Amount & Currency During Payment",
        Date:"Date",
        TransactionHistory:"Transaction History",
        Submit: "Submit",
        OldPassword: "Old Password",
        NewPassword: "New Password",
        OldPin: "Old Pin",
        NewPin: "New Pin",
        ReceiverUsername: "Receiver Username",
        TransactionSuccessfull: "Transaction Successful",
        Details: "Details",
        SenderId: "Sender ID",
        ReceiverId: "Receiver ID",
        AmountIn: "Amount In",
        TransactionId: "Transaction ID",
        Time: "Time"
    },
    hindi: {
        CurrencyConverter : "मुद्रा परिवर्तक",
        Status: "ऑनलाइन स्थिति",
        Home: "घर", 
        LogOut: "लॉग आउट",
        About : "बारे में",
        FromCurrency: "मुद्रा से:",
        ToCurrency: "मुद्रा के लिए: ",
        Amount :"मात्रा",
        Convert : "परिवर्तन",
        Profile: "पार्श्वचित्र",
        Pay: "भुगतान",
        SignIn: "साइन इन करें",
        EnterYourName: "अपना नाम दर्ज करें",
        EnterYourEmailAddress:"अपना ईमेल पता दर्ज करें",
        EnterPassword: "पासवर्ड दर्ज करें",
        SignUp: "साइन अप करें",
        EnterPin: "पिन दर्ज करें",
        MakeAtransaction: "लेन-देन करें",
        Currency: "मुद्रा",
        SixDigPin: "6-अंकीय पिन",
        Reason: "कारण",
        MakePayment:"भुगतान करें",
        ChangePassword: "पासवर्ड बदलें",
        ChangePin: "पिन बदलें",
        Balance: "शेष राशि",
        Email: "ईमेल",
        Username: "उपयोगकर्ता नाम",
        UserId: "उपयोगकर्ता आईडी",
        Edit: "संपादित करें",
        Security:"सुरक्षा",
        PaidTo:"को भुगतान किया",
        AmountAndCurrencyDuringPayment: "भुगतान के दौरान राशि और मुद्रा",
        Date:"तारीख",
        TransactionHistory:"लेन-देन इतिहास",
        Submit: "प्रस्तुत",
        OldPassword: "पुराना पासवर्ड",
        NewPassword: "नया पासवर्ड",
        OldPin: "पुराना पिन",
        NewPin: "नया पिन",
        ReceiverUsername: "रिसीवर उपयोगकर्ता नाम",
        TransactionSuccessfull: "लेन-देन सफल",
        Details: "विवरण",
        SenderId: "प्रेषक आईडी",
        ReceiverId: "प्राप्तकर्ता आईडी",
        AmountIn: "में राशि",
        TransactionId: "लेन-देन आईडी",
        Time: "समय"
    },
    tamil: {
        CurrencyConverter : "நாணய மாற்றி",
        Status: "நிகழ்நிலை நிலை",
        Home: "முகப்பு", 
        LogOut: "வெளியேறு",
        About : "பற்றி",
        FromCurrency: "நாணயம் இருந்து:",
        ToCurrency: "நாணயத்திற்கு:",
        Amount: "தொகை",
        Convert : "மாற்று",
        Profile: "சுயவிவரம்",
        Pay : "பணம்",
        SignIn : "உள்நுழைய",
        EnterYourName: "உங்கள் பெயரை உள்ளிடவும்",
        EnterYourEmailAddress:"உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்",
        EnterPassword: "கடவுச்சொல்லை உள்ளிடவும்",
        SignUp: "பதிவு செய்யவும்",
        EnterPin: "பின் எண்ணை உள்ளிடவும்",
        MakeAtransaction: "பரிமாற்றம் செய்",
        Currency: "நாணயம்",
        SixDigPin: "6- இலக்க பின்",
        Reason: "காரணம்",
        MakePayment:"பணம் செலுத்த",
        ChangePassword: "கடவுச்சொல்லை மாற்று",
        ChangePin: "பின் மாற்று",
        Balance: "சமநிலை",
        Email: "மின்னஞ்சல்",
        Username: "பயனர்பெயர்",
        UserId: "பயனர் ஐடி",
        Edit: "தொகு",
        Security:"பாதுகாப்பு",
        PaidTo:"செலுத்தப்பட்டது",
        AmountAndCurrencyDuringPayment: "பணப் பரிமாற்றத்தின் போது தொகை மற்றும் நாணயம்",
        Date:"தேதி",
        TransactionHistory:"பரிமாற்ற வரலாறு",
        Submit: "சமர்ப்பிக்கவும்",
        OldPassword: "பழைய கடவுச்சொல்",
        NewPassword: "புதிய கடவுச்சொல்",
        OldPin: "பழைய பின்",
        NewPin: "புதிய பின்",
        ReceiverUsername: "பெறுநர் பயனர்பெயர்",
        TransactionSuccessfull: "பரிமாற்றம் வெற்றிகரமாக முடிந்தது",
        Details: "விவரங்கள்",
        SenderId: "அனுப்புநர் ஐடி",
        ReceiverId: "பெறுநர் ஐடி",
        AmountIn: "இல் தொகை",
        TransactionId: "பரிமாற்ற ஐடி",
        Time: "நேரம்"
        
    },
    esp: {
        CurrencyConverter : "Convertidor de divisas",
        Status: "Estado en línea",
        Home: "Inicio", 
        LogOut: "Cerrar sesión",
        About : "Acerca de",
        FromCurrency: "De moneda:",
        ToCurrency:"A moneda:",
        Amount: "Cantidad",
        Convert : "Convertir",
        Profile: "Perfil",
        Pay : "Pagar",
        SignIn : "Iniciar sesión",
        EnterYourName: "Ingrese su nombre",
        EnterYourEmailAddress:"Ingrese su dirección de correo electrónico",
        EnterPassword: "Ingrese la contraseña",
        SignUp: "Registrarse",
        EnterPin: "Ingrese el PIN",
        MakeAtransaction: "Hacer una transacción",
        Currency: "Moneda",
        SixDigPin: "PIN de 6 dígitos",
        Reason: "Razón",
        MakePayment:"Realizar pago",
        ChangePassword: "Cambiar la contraseña",
        ChangePin: "Cambiar el PIN",
        Balance: "Saldo",
        Email: "Correo electrónico",
        Username: "Nombre de usuario",
        UserId: "ID de usuario",
        Edit: "Editar",
        Security:"Seguridad",
        PaidTo:"Pagado a",
        AmountAndCurrencyDuringPayment: "Cantidad y moneda durante el pago",
        Date:"Fecha",
        TransactionHistory:"Historial de transacciones",
        Submit: "Enviar",
        OldPassword: "Contraseña anterior",
        NewPassword: "Nueva contraseña",
        OldPin: "PIN anterior",
        NewPin: "Nuevo PIN",
        ReceiverUsername: "Nombre de usuario del receptor",
        TransactionSuccessfull: "Transacción exitosa",
        Details: "Detalles",
        SenderId: "ID del remitente",
        ReceiverId: "ID del receptor",
        AmountIn: "Cantidad en",
        TransactionId: "ID de transacción",
        Time: "Hora"
        
    },
    jpn: {
        CurrencyConverter : "通貨換算機",
        Status: "オンラインステータス",
        Home: "ホーム", 
        LogOut: "ログアウト",
        About : "約",
        FromCurrency: "通貨から:",
        ToCurrency:"通貨へ:",
        Amount: "金額",
        Convert : "変換",
        Profile: "プロフィール",
        Pay : "支払う",
        SignIn : "サインイン",
        EnterYourName: "名前を入力してください",
        EnterYourEmailAddress:"メールアドレスを入力してください",
        EnterPassword: "パスワードを入力してください",
        SignUp: "サインアップ",
        EnterPin: "PINを入力してください",
        MakeAtransaction: "取引を行う",
        Currency: "通貨",
        SixDigPin: "6桁のPIN",
        Reason: "理由",
        MakePayment:"支払いをする",
        ChangePassword: "パスワードを変更する",
        ChangePin: "PINを変更する",
        Balance: "残高",
        Email: "電子メール",
        Username: "ユーザー名",
        UserId: "ユーザーID",
        Edit: "編集",
        Security:"セキュリティ",
        PaidTo:"支払った相手",
        AmountAndCurrencyDuringPayment: "支払い時の金額と通貨",
        Date:"日付",
        TransactionHistory:"取引履歴",
        Submit: "提出する",
        OldPassword: "以前のパスワード",
        NewPassword: "新しいパスワード",
        OldPin: "以前のPIN",
        NewPin: "新しいPIN",
        ReceiverUsername: "受信者のユーザー名",
        TransactionSuccessfull: "取引成功",
        Details: "詳細",
        SenderId: "送信者ID",
        ReceiverId: "受信者ID",
        AmountIn: "金額",
        TransactionId: "取引ID",
        Time: "時間"
    }
};

export default lang;
